### PR TITLE
Tweak retraction to better match Creality software

### PR DESCRIPTION
**Pull request by EmperorArthur**
This significantly reduced stringing.  I have also tweaked other settings, but feel this helps on its own.

### CODE REVIEW

**Comment by suchmememanyskill** [comment]
A few thoughts just looking at the changes:
- Please do not edit the version, i bulk edit all files on release
- I don't think setting min retraction distance to 0 is a good idea. Can you put that to at least 1mm? (Or explain your reasoning)

I'll let you know once i get a chance to test this.

**Comment by suchmememanyskill** [comment]
Alright, did some quick tests:

1. Default settings
2. Changes from PR
3. Changes from PR but with PA turned off
4. Changes from PR but with PA turned off and detraction set to 60mm/s
5. Changes from PR but with detraction set to 60mm/s

No. 2 has the least stringing but all stringing is concetrated to one side, while no.5 looks the most consistent. All tests were done with PETG

More testing is required i think

**Comment by EmperorArthur** [comment]
Will do for the version.

Which setting is PA?

I am printing new Creality PLA from a filament dryer at 205C. Which matches the Creality default.

Interesting the 60mm is more consistent.  Looking at the gcode from Creality, it detracts at the same speed as retraction.

I'll remove the 0z as well.  That snuck in as I had tried it to help with a seam problem, but have just found a YouTube video stating the Ender 3 V3 SE's firmware doesn't obey gcode acceleration limits, and the default firmware speeds are too high.

More on that in a separate discussion/PR.

**Comment by suchmememanyskill** [comment]
PA = Pressure Advance. It's currently Klipper exclusive (not something you configure in the slicer). It non-linearly spreads the pressure applied to the nozzle so that at the end of an extrude move, the nozzle has no pressure left. It helps with blobby corners and stringing, among other things.

**Comment by EmperorArthur** [comment]
Removed the retract_before_travel change.  I've found I have occasional bed adhesion issues from dust, and not retracting was causing the perimeter to blob up and/or be dragged along.  I solved the issue of small moves with the changes in discussion #18.

With this, it's down to slowing down deretract and the 70% retraction before the wipe.

**Comment by suchmememanyskill** [comment]
Alright, got my hands on some PLA

The PLA was wet at first, causing lots of stringing. After drying, even the current profile gave very good results already. Here are my results:

1. Default settings, PA disabled, 1mm retraction
2. Default settings, PA disabled, 0.8mm retraction
3. Retract amount before wipe: 70%, Minimum travel after retraction: 1, PA disabled, 0.8mm retraction
4. Retract amount before wipe: 70%, PA disabled, 0.8mm retraction
5. Default settings, PA disabled, 0.8mm retraction, no Z-Hop

1. No stringing across, some wisps on the sides
2. Same as one, but very slightly more wisps on the side
3. Lots of tiny strings across the part
4. Lots of tiny strings across the part. Slightly better than 3
5. No stringing across, some wisps on the sides. Equal to 1

To me, the settings edited here are more tricky than i thought. I have no idea why this happens. The only conclusive thing that i got out of this is that no Z hop does have a positive effect

**Comment by EmperorArthur** [comment]
Hey, glad to see someone else's results! Your number 2 result doesn't match mine, but that may be down to the model and PLA used.

The only thing I don't see tested is adjusting the deretract speed.  If your testing shows no difference on that setting with PLA, I'll just close this PR as not worth it.

**Comment by suchmememanyskill** [comment]
I have not tested yet with decreasing detraction speed: if i can get better results using different settings, then why should i slow down retractions by quite a bit?

I can still test it if you want but i suspect disabling Z hop would be more effective

**Comment by EmperorArthur** [comment]
Closing PR, since there are likely better methods.

**Pull request closed without merging**
