### PR TITLE
Changed deretraction speed and retraction length.

### PR DESCRIPTION
**Pull request by ak-tr**
I had much better results when trying to mitigate stringing when adjusting the values as mentioned.

### CODE REVIEW

**Comment by suchmememanyskill** [comment]
Will test whenever i have time. I think 1.5mm retraction is a bit excessive, but i do agree it should probably be higher

**Comment by ak-tr** [comment]
> Will test whenever i have time. I think 1.5mm retraction is a bit excessive, but i do agree it should probably be higher

To be fair, these are the retraction settings I had in Creality Print by default and I never had barely any stringing issues.

**Comment by suchmememanyskill** [comment]
Tested using PLA with current settings, 40mm detract speed + 1.2mm retract length and 40mm detract speed + 1.5mm retract length. 1.5mm retract looks the best but i'm using pretty damp filament for this to make stringing more obvious.

I think it would make more sense to decrease retraction to 1.4 to match [the petg profile](https://github.com/suchmememanyskill/PrusaSlicer-Ender3-v3-SE-Config/blob/main/PrusaSlicer/filament/PETG%20230C%2070C.ini#L36). Would you mind changing retraction length to 1.4mm and also applying them to the Klipper flavor of the print profile?

**Comment by ak-tr** [comment]
I have added the changes as requested.

**Comment by suchmememanyskill** [comment]
After a 2 hour print i see very little stringing, a lot less than it did before

LGTM, thank you!

**Pull request merged**
